GoogleCloudPlatform/marketplace-k8s-app-tools

- marketplace/dev/Dockerfile
This pull simplifies the handling of kubectl credentials files (removing need to mount volumes) and improves Cloudbuild performance (`gcr.io/cloud-builders/gcloud` image is already cached).
> Reparenting marketplace/dev image to be based on official gcloud image.

- app.Makefile
- marketplace.Makefile
- marketplace/deployer_util/config_helper.py
- marketplace/deployer_util/config_helper_test.py
- marketplace/deployer_util/expand_config_test.py
- marketplace/deployer_util/print_app_api_version.py
- scripts/install
Also include a few fixes to broken Makefiles, and a short-term fix for gcloud config overriding, as indicated in #207.
> Use applicationApiVersion, still supporting old name

- app.Makefile
* Add `EXTRA_DOCKER_PARAMS` for use cases link `EXTRA_DOCKER_PARAMS="--link metadata:metadata.google.internal"`.
* Convert `--volume` flags to `--mount` (easier debugging).
> Adjustments to app.Makefile.

- marketplace/deployer_helm_base/create_manifests.sh
The previous `ls -Al` implementation didn't work in my testing.
> More reliably find chart tars

- marketplace/deployer_util/provision.py
- marketplace/deployer_util/provision_test.py
Also corrects the value passed to the labels.
> Limit the length of names of RBAC resources.

- testrunner/specs/specs.go
- testrunner/specs/specs_test.go
- testrunner/specs/testdata/suite.json
- testrunner/specs/testdata/suite.yaml
- testrunner/tests/bash.go
- testrunner/tests/bash_test.go
Keeping the API of BashTest consistent with the rest.
For any more complex assertion, we can add more conditions,
such as `satisfyingExpression: <string expression>`.
#268
> Do not use arrays in expect

- testrunner/README.md
ERROR: (gcloud.container.builds.submit) This command has been replaced with `gcloud builds`.
> Fix gcloud command

- marketplace/dev/bin/setup_config.sh
Application default credential config does not have
cmd-path set. The old code incorrectly set a new cmd-path,
which would make credential refreshing fail.
> Only overwrite gcloud command if it exists

- marketplace/deployer_helm_base/create_manifests.sh
- marketplace/deployer_helm_tiller_base/bin/deploy_internal.sh
- marketplace/deployer_util/print_config_test.py
Command and process substitution failures do not propagate to the calling script.
I considered (1) using variable for command substitution, which doesn't work either, and (2) writing processing substitution outputs to temporary files. I settled on this as it achieves the same result, and as the same time prints out useful diagnosis log messages.
> Fail deployer if config errors

- marketplace/dev/Dockerfile
This ensures that docker client run from within the dev container will
call gcloud to handle authentication/authorization handshake.
> Add docker gcr configuration to dev image build.

- cloudbuild-tag.yaml
- cloudbuild.yaml
Turns out that `index.yaml` in the directory (rather than the merge file) is updated.
Honestly, I'm unclear as to how the helm/charts repository works, given [this](https://github.com/helm/charts/blob/master/test/repo-sync.sh#L90) line.
> Fix index.yaml update in cloudbuild.yaml and cloudbuild-tag.yaml.

- docs/schema.md
- marketplace/deployer_helm_tiller_base/bin/deploy.sh
- marketplace/deployer_helm_tiller_base/bin/deploy_internal.sh
- marketplace/deployer_util/config_helper.py
- marketplace/deployer_util/config_helper_test.py
- marketplace/deployer_util/expand_config.py
- marketplace/deployer_util/expand_config_test.py
- tests/marketplace/deployer_helm_tiller_base/onbuild/standard/chart/minimal-helm-chart/templates/application.yaml
- tests/marketplace/deployer_helm_tiller_base/onbuild/standard/schema.yaml
Some helm charts wish to use global.application.create value
to control whether the Application resource should be included
in the generated manifests. This is the negation of the truthy
value of the existing APPLICATION_UID property.
> Support boolean application create property

- marketplace/deployer_helm_tiller_base/bin/deploy_internal.sh
- marketplace/deployer_helm_tiller_base/bin/post-delete.sh
- marketplace/deployer_helm_tiller_base/bin/post-install.sh
- marketplace/deployer_util/deploy.sh
- marketplace/deployer_util/deploy_with_tests.sh
- marketplace/deployer_util/patch_assembly_phase.sh
- marketplace/deployer_util/wait_for_ready.py
- scripts/install
- scripts/verify
- scripts/watch.sh
Use `applications.app.k8s.io` instead of the short name for the applications CRD.
This hardens the tooling for environments where there might be a conflict on 
the `applications` short name and some other API group is prioritized by Kubernetes
discovery.
Fixes #321
> Use full app CRD resource name

- docs/schema.md
- marketplace/deployer_util/config_helper.py
- marketplace/deployer_util/config_helper_test.py
Introducing schema file x-google-marketplace properties:
- Compatibility flag
```yaml
x-google-marketplace:
istio:
isSupported: True # Indicates whether the app is compatible with Istio.
```
- Deployer property
```yaml
properties:
- name: istioEnabled
type: ISTIO_ENABLED # Indicates whether the app is being deployed with Istio.
```
>  Adding istio types in schema files

- cloudbuild-tag-prerelease.yaml
This is used for building pre-releases, which is a way to push out candidates without affecting our main users.
The difference between this and `cloudbuild-tag.yaml` is that this one never updates the `latest` tags in GCR.
> Add cloudbuild-tag-prerelease

- scripts/verify
This property can be used to tell the verifier what imagePullSecret to use.
This change is needed by on-prem verification.
> Adding image_pull_secret property to verifier

- marketplace/deployer_util/config_helper.py
- marketplace/deployer_util/config_helper_test.py
- marketplace/deployer_util/expand_config_test.py
- marketplace/deployer_util/print_config_test.py
Although unused in the final deployment, these values are key for the publishing process since they indicate which staging GCR repo values to copy.
/gcbrun
> Validate default value for IMAGE properties in schema v1

- tests.Makefile
- tests/marketplace/deployer_helm_tiller_base/onbuild/standard_v2/chart/minimal-helm-chart/templates/application.yaml
- tests/marketplace/deployer_helm_tiller_base/onbuild/standard_v2/run_test
See that .tests/marketplace/deployer/helm_tiller_onbuild/standard_v2 is currently broken in [PR#391](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/pull/391).
/gcbrun
> Fix helm standard_v2 test and add to helm_tiller_onbuild make target

- docs/schema.md
RBAC rule resource references must be the lowercase-plural name (e.g. as shown in `kubectl api-resources`). The kind or singular form does not work.
/gcbrun
> Fix resources RBAC rule resource refs in schema doc

- marketplace/deployer_util/provision.py
- marketplace/deployer_util/provision_test.py
Differentiate names for ClusterRole{,Binding}s from Role{,Binding}s with a 'c'.
Also reduce test fragility by ignoring list order.
/gcbrun
> Fix name for provisioned ClusterRole{,Binding}s

- marketplace/deployer_util/resources.py
- marketplace/deployer_util/resources_test.py
- marketplace/deployer_util/set_ownership.py
Prevent applying OwnerRefs that do not comply with the [Kubernetes spec](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents) (which forbids namespaced resources owning cluster-scoped resources).
/gcbrun
> Only apply the App OwnerRef to namespaced resources

- marketplace/deployer_util/provision.py
- marketplace/deployer_util/provision_test.py
Replace the `<app-name>-deployer-r` pattern which was partially switched to `<app-name>:deployer-r` in [PR #381](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/pull/381/files)
/gcbrun
> Make deployer IAM resource naming consistent

- marketplace/deployer_util/config_helper.py
- marketplace/deployer_util/config_helper_test.py
Ensure that SERVICE_ACCOUNT properties are validly formed to catch errors early. Otherwise, issues only surface when the property is parsed in the UI.
/gcbrun
> Validate SERVICE_ACCOUNT roles

- scripts/verify
By running `jq ".$key = value`, any value of `$key` with a period would create a parameters payload with nested values. However, later scripts (e.g. deployment) assume that parameters is a flat payload.
For example, my reporting secret is stored in a key named "ubbagent.reportingSecret". During verify, this parameter is inferred by `extract_schema_key.py`. After a fake secret is created, the key is added to the parameters payload using `"echo $parameters | jq ".ubbagent.reportingSecret" = "some-key-name"`. The resulting payload is:
```json
{
"name": "...",
"namespace": "...",
"ubbagent": {
"reportingSecret": "some-key-name",
}
}
```
This is wrong, and causes later steps to fail with "no property defined in schema: ubbagent". Instead, the parameters struct should be:
```json
{
"name": …
```
> Fix bug in verify script preventing the use of '.' in marketplace-reserved keys

- marketplace/deployer_helm_base/Dockerfile
Helm 2.8.1 doesn't support ternary in YAML files. 
In this example, used by Postgres chart (https://github.com/helm/charts/blob/master/stable/postgresql/templates/statefulset.yaml, rows 121 and 202) ternary won't be parsed and deployment will fail. 
```value: {{ ternary "true" "false" .Values.image.debug | quote }}```
Error message: "Error: parse error in "artifactory-ha/charts/postgresql/templates/statefulset.yaml": template: artifactory-ha/charts/postgresql/templates/statefulset.yaml:121: function "ternary" not defined"
To resolve this problem we need to use the latest version of Helm in the Deployer dockerfile.
> Use latest Helm version - 2.16.1, which supports ternary function.

- marketplace/deployer_util/clean_iam_resources.sh
- marketplace/deployer_util/magic_schema.sh
- marketplace/deployer_util/make_dns1123_name.py
- marketplace/deployer_util/provision.py
- marketplace/deployer_util/set_ownership.py
- scripts/install
Set the deployer service account as owner of it's component resources (i.e. Role and RoleBinding) during install (already done during UI deployment), then only delete the deployer ServiceAccount after deployment, rather than also explicitly deleting the Role and Rolebinding.
Addresses #347:
Partners must update their base deployer to take advantage of this change, which is to only delete the deployer service account after deployment instead of also attempting to delete its dependent resources to avoid deletion timing problems.
/gcbrun
> Make OwnerRefs handle cleanup of deployer's RBAC resources

- marketplace/deployer_util/provision.py
The deployer will encounter errors if there aren't enough resources
for it to run successfully. This sets the minimum values for the
deployer:
- cpu: 1m
- memory: 2Mi
> Setting minimum required cpu and memory values for the deployer

- Makefile
There was a breaking change to yapf. See changelog here:
https://github.com/google/yapf/blob/51ffe2d07930a509ecb2ef454a7b251eeeac0a59/CHANGELOG#L17
> Change yapf style from chromium to yapf

- marketplace/deployer_util/provision.py
- marketplace/deployer_util/provision_test.py
Due to apps failing for `unknown` permission failures.
Created by checking out the modified files from the previous commit:
```shell
git checkout 5749bf28fdcd320074348513c22855f88734ce37 marketplace/deployer_util/provision.py
git checkout 5749bf28fdcd320074348513c22855f88734ce37 marketplace/deployer_util/provision_test.py
```
/gcbrun
> Revert deployer permissions to  in namespace

- Makefile
To fix `make format/py` (https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/issues/503)
/gcbrun
> Update yapf style name

- marketplace/deployer_util/provision.py
- marketplace/deployer_util/set_ownership.py
1. Change label for deployer-owned RBAC resources so that the deployer does not attempt to delete them manually (causes https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/issues/347), leaving cleanup to OwnerRefs
2. Only set the deployer ServiceAccount as owner of deployer-wned RBAC resources (instead of also setting the Application as owner) so that they are cleaned up along with the deployer ServiceAccount instead of only on Application deletion (as deletion occurs only when all owners have been deleted; see [API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#objectmeta-v1-meta)).
/gcbrun
> Update cleanup for deployer-owned RBAC resources

- marketplace/deployer_util/deploy_with_tests.sh
- marketplace/deployer_util/resources.py
- marketplace/deployer_util/set_ownership.py
To prevent leaving orphaned resources in `mpdev verify`, improving the reliability of tests.
No update to `mpdev install` or end-user flows, as the desired handling of cluster-scoped resources is unclear.
/gcbrun
> Set the namespace as owner of cluster-scoped resources in verify

- scripts/verify
Cloud build has a limit of 4k characters in the command line. All the images need to be overwritten in the parameters, which can cause the character limit to be reached for a few solutions.
This reduces the number of characters in the parameters to avoid the limit.
> Allow scripts/verify to consume parameters from GCS

- docs/billing-integration.md
As the metric type should be `double` instead of `float` ([example](https://github.com/GoogleCloudPlatform/ubbagent/blob/b20a3bf0ac380ad27c02141d4d528de5175424a1/metrics/report_test.go#L32)).
/gcbrun
> Refer to 'double' instead of 'float'

- marketplace/deployer_util/config_helper.py
- marketplace/deployer_util/config_helper_test.py
For user security and transparency.
Makes the restriction from #521 apply to all service accounts instead of only the `deployerServiceAccount`.
/gcbrun
> Disallow vague escalated permissions on all service accounts

- docs/schema.md
Update docs now that `cluster-admin` is now disallowed in `SERVICE_ACCOUNT`properties. Recommend that `deployerServiceAccount` is used when long-lived service accounts are not needed.
/gcbrun
> Update schema docs for restricted SERVICE_ACCOUNT permissions

- marketplace/deployer_util/provision.py
- marketplace/deployer_util/provision_test.py
- scripts/install
- scripts/verify
Introducing optional property storage_class_provisioner
Usage:
mpdev verify --deployer="$DEPLOYER" --wait_timeout="$WAIT_TIMEOUT" --image_pull_secret="$IMAGE_PULL_SECRET" --storage_class_provisioner=kubernetes.io/vsphere-volume
Supported values:
kubernetes.io/vsphere-volume
kubernetes.io/gce-pd
If no value is provided, kubernetes.io/gce-pd is used by default
> Allow selection of storage class provisioner in mpdev

- marketplace/deployer_util/provision.py
- marketplace/deployer_util/provision_test.py
Pods can be unscheduable due to a Volume Node Affinity Conflict. This can happen when a pod has multiple pvcs, but the persistent volumes were created in different zones and thus not all pvs could be attached.
Kubernetes documentation suggests using WaitForFirstConsumer to avoid these issues. https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode
> Use WaitForFirstConsumer for GCP PersistentDisks

- marketplace/deployer_util/provision.py
This is required to run verification in baremetal clusters, where there is no storage provisioner. More on storage provisioners at https://kubernetes.io/docs/concepts/storage/storage-classes/#local
> Support kubernetes.io/no-provisioner

- cloudbuild.yaml
- docs/mpdev-references.md
- marketplace/deployer_helm_base/create_manifests.sh
- marketplace/deployer_util/constants.py
- marketplace/deployer_util/deploy_with_tests.sh
- marketplace/deployer_util/overlay_test_schema.py
- marketplace/deployer_util/run_tester.py
- scripts/dev
- scripts/verify
Output from verify is very big and hard to consume. This change try to make troubleshooting easier by separating different sessions of the output in multiple files:
verify.log
The entire output. It includes the deployer logs
deployer.log
Only the log from deployer. It includes the tester logs.
tester.log
Only logs from the tester.
events.log
All the events collected before deleting the namespace
resources.yaml
All the resources that were applied. This session is huge and not often useful, so it is now removed from the output.
> Creating multiple log files for mpdev verify

- cloudbuild-tag-prerelease.yaml
- cloudbuild-tag.yaml
- cloudbuild.yaml
- marketplace/charts/marketplace-integration/Chart.yaml
- marketplace/deployer_envsubst_base/Dockerfile
- marketplace/deployer_helm_base/Dockerfile
- marketplace/dev/Dockerfile
- scripts/dev
* Upgrade kubectl to [current GKE versions](https://cloud.google.com/kubernetes-engine/docs/release-notes#current_versions) (1.21.11, 1.22.8, 1.23.5).
* Upgrade helm to 3.8.2.
* Use marketplace.gcr.io/google/ubuntu2004 as base images: using Ubuntu 20.04 will probably have better compatibility with the old google/python image (which is based on ubuntu 16.04), and is less likely break downstream images. Also, CVE-2015-20107 is marked as Low Severity on Ubuntu 20.04 by GCR Vulnerability Scanning, whereas on Debian 11 it is marked as Critical.
* Use a new `DOCKER_NETWORK` env var to override the Docker network in the `dev` script (default value is `host`; test script overrides it with `cloudbuild`): with the current way of using `EXTRA_DOCKER_PARAMS`, we get an error `docker: conflicting …
> Upgrade kubectl and helm versions and change base image to Ubuntu 20.04

- scripts/verify
Needed to make executions of `scripts/verify` work outside of the context of `scripts/dev`. Has no effect if there is already a `/logs` directory.
/gcbrun
> Ensure the /logs directory exists

- marketplace/deployer_util/clean_iam_resources.sh
From a test run
```
DEPLOYER serviceaccount "apptest-bple947l-deployer-sa" deleted
DEPLOYER error: You must be logged in to the server (Unauthorized)
```
`kubectl` can no longer log into the server because we just deleted the deployer service account, and calling `kubectl delete` without `--wait false` means we're effectively calling `kubectl wait` without credentials
> Do not wait for deployer service account deletion

- scripts/dev
mpdev verify can sometimes only be killed via pkill -9 -f verify as ctrl + c does not work.
Possibly related to https://stackoverflow.com/questions/31350335/docker-not-responding-to-ctrlc-in-terminal and we just need to add --init to https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/fd8b9e630e1ea0d34349bc2b27da7ba7da0bb964/scripts/dev#L43
> Fix SIGINT handling

- docs/schema.md
The UI does not support custom TLS_CERTIFICATE property.
If a partner requires a custom TLS_CERTIFICATE, they can add a "certificate" STRING property and "privateKey" `MASKED_FIELD property
> Remove custom TLS_CERTIFICATE from documentation

- marketplace/deployer_envsubst_base/Dockerfile
- marketplace/deployer_helm_base/Dockerfile
- marketplace/dev/Dockerfile
* kubectl versions updated to 1.23.13 1.24.7 1.25.4 following https://cloud.google.com/kubernetes-engine/docs/release-notes
* helm updated to 3.10.3 from https://github.com/helm/helm/releases
> Update helm and kubectl to latest versions

- marketplace/deployer_util/process_helm_hooks.py
Helm v3 introduces test helm hook which should be filtered same reason you see `test-success` and `test-failure`.
#569
> add support for ignoring test hook from helm v3

- marketplace/deployer_envsubst_base/Dockerfile
- marketplace/deployer_helm_base/Dockerfile
- marketplace/dev/Dockerfile
updating kubectl and helm versions
> updating kubectl and helm versions

- docs/building-deployer-helm.md
The helm chart location has moved, this updates that link.
Ref: https://helm.sh/blog/new-location-stable-incubator-charts/
> Update location of helm charts
