marketplace/deployer_util/wait_for_ready.py
marketplace/dev/setup_kubeconfig.sh
scripts/driver/driver.sh
scripts/driver/driver_internal.sh
scripts/start.sh

This change mitigates failures due to gcloud failure to write to logs or `credentials.db` and includes addition of diagnostic information to `driver_internal.sh`.

Copy mounted gcloud configuration in marketplace/dev.

---

marketplace/deployer_util/config_helper.py
marketplace/deployer_util/expand_config.py
marketplace/deployer_util/wait_for_ready.py
testing/py/Dockerfile

To fix failing daily CI: https://travis-ci.com/GoogleCloudPlatform/marketplace-k8s-app-tools

Fix lint (new linter version?)

---

app.Makefile
marketplace/deployer_util/deploy.sh
marketplace/deployer_util/deploy_with_tests.sh
marketplace/deployer_util/print_config.py
marketplace/deployer_util/print_config_test.py
scripts/install

Also refactor `--param` to `--xtype` and retrofitted existing invocations.

Add --key to print_config.py.

---

cloudbuild.yaml
testing.Makefile

Also remove ubbagent submodule.
We should reorganize our Makefiles, too, but let's consider that out of scope for this pull request.

Add integration tests to cloudbuild.yaml.

---

cloudbuild.yaml

This pull request fixes our CI/CD.

Increase timeout and parallelize integration tests.

---

testrunner/examples/testspecs/bash.yaml

Follow up: https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/pull/270

Fix examples (bash.yaml)

---

testrunner/runner/BUILD

Comment was about removing binary_srcs and binary_deps, not about load

Follow up to PR/289

---

marketplace/deployer_util/wait_for_ready.py

Job status:
```yaml
status:
completionTime: 2019-02-11T15:36:54Z
conditions:
- lastProbeTime: 2019-02-11T15:36:54Z
lastTransitionTime: 2019-02-11T15:36:54Z
status: "True"
type: Complete
startTime: 2019-02-11T15:36:52Z
succeeded: 1
```
Pod status:
```yaml
status:
conditions:
- lastProbeTime: null
lastTransitionTime: 2019-02-11T16:51:01Z
status: "True"
type: Initialized
- lastProbeTime: null
lastTransitionTime: 2019-02-11T16:51:01Z
message: 'containers with unready status: [command-demo-container]'
reason: ContainersNotReady
status: "False"
type: Ready
- lastProbeTime: null
lastTransitionTime: 2019-02-11T16:51:01Z
status: "True"
type: PodScheduled
```

Wait for Pod & Job to be ready

---

scripts/verify

The verify script needs to set the ISTIO_ENABLED to true to communicate the deployer that Istio should be handled.

Set ISTIO_ENABLED=true in verify for istio=enabled

---

marketplace/deployer_util/provision.py
scripts/install

The version file implies both deployer image and
version repo.

Install from version file

---

marketplace/deployer_util/expand_config.py
marketplace/deployer_util/property_generator.py
marketplace/deployer_util/provision.py
marketplace/dev/Dockerfile

These values have to remain the same across updates.

Generate passwords and TLS certificates at provisioning time

---

marketplace/deployer_helm_tiller_base/bin/deploy_internal.sh
marketplace/deployer_util/provision.py

This doesn't use KALM, but at least it enables testing of
deployers using v2 schema.

Support helm tiller upgrade and fix verify

---

scripts/dev

Fix readlink for Mac

---

marketplace/deployer_util/config_helper.py
marketplace/deployer_util/config_helper_test.py
marketplace/deployer_util/expand_config_test.py
marketplace/deployer_util/print_config_test.py

Ran make format/py to fix python linter errors.

Fixing the broken build

---

tests.Makefile
tests/marketplace/deployer_envsubst_base/standard_v2/Dockerfile
tests/marketplace/deployer_envsubst_base/standard_v2/manifest/application.yaml
tests/marketplace/deployer_envsubst_base/standard_v2/manifest/pod.yaml
tests/marketplace/deployer_envsubst_base/standard_v2/run_test
tests/marketplace/deployer_envsubst_base/standard_v2/schema.yaml

Add an envsubst standard_v2 test app

---

marketplace/deployer_util/config_helper.py
marketplace/deployer_util/config_helper_test.py

Support MASKED_FIELD x-google-marketplace type

---

docs/schema.md

Add documentation for MASKED_FIELD x-google-marketplace type

---

docs/schema.md

Fix for https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/issues/406

Documented DEPLOYER_IMAGE property

---

marketplace/deployer_util/separate_tester_resources.py
marketplace/deployer_util/set_app_labels.py
marketplace/deployer_util/set_ownership.py

Fix 'applictation' typo

---

marketplace/deployer_util/config_helper.py
marketplace/deployer_util/config_helper_test.py

Validate schema publishedVersion value

---

marketplace/deployer_util/config_helper.py
marketplace/deployer_util/config_helper_test.py

Use semver.org regex for publishedVersion validation

---

marketplace/deployer_envsubst_base/Dockerfile
marketplace/deployer_helm_base/Dockerfile
marketplace/deployer_helm_tiller_base/Dockerfile
marketplace/deployer_util/kubectl
marketplace/dev/Dockerfile
scripts/dev

Also add `-it` to mpdev's `docker run` invocation so that it can be Ctrl-C'ed.
Fixes #404.

Select the best version of kubectl to use

---

marketplace.Makefile

Add helm_onbuild target to marketplace.Makefile

---

docs/schema.md

Add documentation for requiredOauthScopes

---

marketplace/deployer_util/set_ownership.py

As it is against the [Kubernetes spec](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents) for cluster-scoped resources to be owned by a namespaced resource (i.e. the Application).
Follow-up to [PR #417](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/pull/417).
/gcbrun

Avoid OwnerRef on cluster-scoped resources in all cases

---

marketplace/deployer_util/clean_iam_resources.sh
marketplace/deployer_util/provision.py

Update TODO statements

---

docs/tool-prerequisites.md

Missed documentation update from #324.
Addresses #451.
/gcbrun

Fix prereqs doc command for doctor script

---

marketplace/deployer_util/resources.py
marketplace/deployer_util/resources_test.py
marketplace/deployer_util/separate_tester_resources.py
marketplace/deployer_util/set_ownership.py

Support service account kind as owner in resources util

---

docs/schema.md

Remove GCP/OAuth schema docs

---

.gitignore
tests.Makefile
tests/py/Dockerfile
tests/py/runtests.sh

Output looks like this:
```
Ran 94 tests in 0.475s
OK
+ coverage report -m
Name                           Stmts   Miss  Cover   Missing
------------------------------------------------------------
__init__.py                        2      2     0%   1-3
bash_util.py                      42     28    33%   28-39, 42, 45-57, 60-66, 69, 73
config_env.py                     26     26     0%   17-64
config_helper.py                 482     25    95%   67, 71, 76-94, 164, 209, 302
config_helper_test.py            303      1    99%   1217
constants.py                       2      2     0%   15-17
```

Add unit test coverage to make tests/py

---

docs/schema.md

Remove GCP docs (OAuth) since feature not yet available

---

docs/building-deployer-helm.md
docs/managed-updates.md
docs/schema.md

Update docs for the now-optional primary app image

---

docs/schema.md

Remove missed line on primary app image requirement

---

docs/building-deployer.md

Clarify that image pushing does not automatically submit a new version

---

docs/verification-integration.md

Provide troubleshooting instructions for the error:
No value for required property: \<propertyName\>

No value for required property: <propertyName>

---

docs/schema.md

Specify UI use of `clusterConstraints.resources`

---

marketplace/deployer_util/config_helper.py
marketplace/deployer_util/config_helper_test.py

Add support and validation for GPU in clusterConstraints

---

docs/schema.md

Only merge after #481 is released.
/gcbrun

Update schema docs for GPU requests

---

docs/billing-integration.md

Improve doc for heart beat metric reported value

---

marketplace/deployer_util/provision.py
marketplace/deployer_util/provision_test.py

Instead use `admin` and a custom Role for modifying Application CRs.

Stop using `cluster-admin` for deployer

---

scripts/verify

Print an explict PASSED/FAILED status in verify

---

marketplace/deployer_util/setassemblyphase.py

Note: partners will have to use a base deployer with this change in order to receive the additional messaging.
/gcbrun

Link documentation to failure message for missing Application resource

---

docs/schema.md

Add deployerServiceAccount docs

---

docs/schema.md

Adding assistedClusterCreation docs.

add assistedClusterCreation docs

---

marketplace/deployer_util/schema_values_common.py
scripts/verify

Fix load_schema_and_validate()

---

marketplace/deployer_envsubst_base/Dockerfile
marketplace/deployer_helm2_base/Dockerfile
marketplace/deployer_helm_base/Dockerfile
marketplace/deployer_helm_tiller_base/Dockerfile

Update kubectl versions in deployer images

---

docs/billing-integration.md

Clarify reporting metric granularity recommendation

---

docs/schema.md

Correct k8sVersion format in schema.md

---

tests/marketplace/deployer_helm2_base/onbuild/standard_v2/chart/minimal-helm-chart/templates/crontab-crd.yaml
tests/marketplace/deployer_helm2_base/onbuild/standard_v2/schema.yaml

Demonstrate creating a CRD (no CR) using the `deployer_helm2_base.`
/gcbrun

Add CRD example to deployer_helm2 test

---

crd/app-crd.yaml

Updating the application crd schema to include the v1alpha1 version for v1.22 k8s

Updating the Application CRD schema to include v1alpha1

---

docs/schema.md

Remove schema docs only relevant to managed updates

---

marketplace/deployer_envsubst_base/Dockerfile
marketplace/deployer_helm_base/Dockerfile
marketplace/dev/Dockerfile

* `kubectl` versions updated to 1.21.12, 1.22.8, 1.23.7 following https://cloud.google.com/kubernetes-engine/docs/release-notes
* `helm` updated to 3.9.0 from https://github.com/helm/helm/releases

Upgrade helm and kubectl to latest versions

---

marketplace/deployer_util/config_helper.py
marketplace/deployer_util/config_helper_test.py

To enable valid uses of these permissions.
/gcbrun

Allow specifically-listed cluster-scoped verbs

---

marketplace/deployer_envsubst_base/Dockerfile
marketplace/deployer_helm_base/Dockerfile
marketplace/deployer_util/provision.py
marketplace/dev/Dockerfile

Quarterly SaaP base container image update

Update helm and kubectl

---

marketplace/deployer_helm_base/Dockerfile
marketplace/dev/Dockerfile

kubectl is already at 1.27.3 and 1.28.3
update helm to v3.13.3

Update helm version

---

marketplace/deployer_envsubst_base/Dockerfile
marketplace/deployer_helm_base/Dockerfile
marketplace/dev/Dockerfile

Update helm and kubectl version

Update helm and kubectl version

---

marketplace/deployer_envsubst_base/Dockerfile
marketplace/deployer_helm_base/Dockerfile
marketplace/dev/Dockerfile

* Update helm to 3.17.2
* Update kubectl versions to 1.30.4 1.31.0

Update helm and kubectl versions
